source 'https://binrepo.target.com/artifactory/api/gems/basetgt-gems/'
source 'https://binrepo.target.com/artifactory/api/gems/basetgt-gem-local/'

gem 'rake'
gem 'chefspec'
gem 'foodcritic'
gem 'rubocop'
gem 'berkshelf'
gem 'chef-vault'
gem 'chef-vault-testfixtures' 
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'ohai'
gem 'chef'
